### ISSUE TITLE
why does it work differently in node and in the browser?

### ISSUE THREAD

**Issue by MedinaGitHub** [vogtb/spreadsheet#3]
in node resolves function, but in browser writes function

sheet.getCell("B1").getValue(); // returns: 1123.1

but en browser works this sheet.getCell("B1").getValue(); // returns: "=SUM(A1:A5)"

**Comment by MedinaGitHub** [comment]
please help me !

**Comment by MedinaGitHub** [comment]
+1

**Comment by vogtb** [comment]
Hey there, sorry, I just saw this now - I'm not actively maintaining this project. I've only tested this in node, so I can't be sure why it's not working in the browser. If you figure it out, feel free to submit a pull-request!
