### ISSUE TITLE
Reverse a formula

### ISSUE THREAD

**Issue by yboujraf** [vogtb/spreadsheet#4]
Dear @twobit , @vogtb  

'$' is the value provided by a sensor or by the client side (display value)
I got from the manufacturer the formula to calculate the expression.

- Manufacturer side ($)-> Client (display the value in a correct format) I calculate the expr1
- Client side ($) -> Manufacturer  (send to the sensor the correct value f.e. change the temperature of the room)  I calculate the expr2

Some examples

- expr1 = 1 + log($, 2) 
- expr2 = 2^($ - 1) 

- expr1 = sin($ / 7.43) where $ is of type INTEGER 
- expr2 = int(7.43 * asin($)) 

- expr1 = $ - log($ / (e^(-$) * $^sin(1 / $)), 10) 
- expr2 = exercise left to the reader  

My question is :

Is it possible with your library to calculate the reverse formula of one of the expression (expres1 or expres2) depending which expression the manufacturer provide us.

Thanks in advance if you could route me to the correct solution.

Best Regards
Youssef

**Comment by yboujraf** [comment]
Dear @twobit , @vogtb  

'$' is the value provided by a sensor or by the client side (display value)
I got from the manufacturer the formula to calculate the expression.

- Manufacturer side ($)-> Client (display the value in a correct format) I calculate the expr1
- Client side ($) -> Manufacturer  (send to the sensor the correct value f.e. change the temperature of the room)  I calculate the expr2

Some examples

- expr1 = 1 + log($, 2) 
- expr2 = 2^($ - 1) 

- expr1 = sin($ / 7.43) where $ is of type INTEGER 
- expr2 = int(7.43 * asin($)) 

- expr1 = $ - log($ / (e^(-$) * $^sin(1 / $)), 10) 
- expr2 = exercise left to the reader  

My question is :

Is it possible with your library to calculate the reverse formula of one of the expression (expres1 or expres2) depending which expression the manufacturer provide us.

Thanks in advance if you could route me to the correct solution.

Best Regards
Youssef

**Comment by vogtb** [comment]
@yboujraf this library might be able to solve individual expressions like this if you replace `$` with the number or a variable that resolves to a number (eg `=2^(A8 - 1)`), but it's not intended to balance equations.

Best,
Ben

**Comment by yboujraf** [comment]
Dear

Thanks for your quick response.

Do you have any idéa for how to do that?

Best regards
Youssef
